


# Server Configuration
server.port=8080
spring.application.name=event-gateway

# Database Configuration (H2 In-Memory)
spring.datasource.url=jdbc:h2:mem:gatewaydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# H2 Console (Accessible at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Actuator & Health Check Configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# Resilience4j Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.accountService.sliding-window-size=10
resilience4j.circuitbreaker.instances.accountService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.accountService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.accountService.wait-duration-in-open-state=10000ms
resilience4j.circuitbreaker.instances.accountService.permitted-number-of-calls-in-half-open-state=3

# Resilience4j Timeout / TimeLimiter Configuration
resilience4j.timelimiter.instances.accountService.timeout-duration=3s

# Logging & Distributed Tracing (Structured Output with Trace ID)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [traceId=%X{traceId:-} spanId=%X{spanId:-}] - %msg%n
logging.level.com.eventledger.gateway=INFO

# External Services
account.service.url=http://localhost:8081


# Tell Spring Boot to trace 100% of incoming requests (1.0 = 100%, 0.1 = 10%)
management.tracing.sampling.probability=1.0

# Format console logs to include [traceId=... spanId=...] automatically
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [traceId=%X{traceId:-} spanId=%X{spanId:-}] - %msg%n



